---
image: node:alpine
definitions:
  caches:
    npm: ~/.npm
    jest: .jest
pipelines:
  default:
      - step:
          name: Test with Jest
          caches:
            - npm
            - jest
          script:
            - npm ci
            - npm run ci-test
  branches:
    develop:
      - parallel:
          - step:
              name: Test with Jest
              caches:
                - npm
                - jest
              script:
                - npm ci
                - npm run ci-test
          - step:
              name: Deploy to Expo
              trigger: manual
              deployment: production
              caches:
                - npm
              script:
                - apk add --no-cache bash
                - npm ci
                - npm install -g expo-cli 6.0.5
                - npx expo publish --non-interactive
    master:
      - step:
          name: Test with Jest
          caches:
            - npm
            - jest
          script:
            - npm ci
            - npm run ci-test
      - step:
          name: Deploy Development Build to Expo
          deployment: staging
          caches: 
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npx eas-cli build --platform all --profile preview --non-interactive
      - step:
          name: Deploy to Expo
          trigger: manual
          deployment: production
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npm install -g expo-cli
            - npx expo publish --non-interactive
