---
image: node:alpine
definitions:
  caches:
    npm: ~/.npm
    jest: .jest
pipelines:
  default:
      - step:
          name: Test with Jest
          caches:
            - npm
            - jest
          script:
            - npm ci
            - npm run ci-test
  branches:
    develop:
      - parallel:
          - step:
              name: Test with Jest
              caches:
                - npm
                - jest
              script:
                - npm ci
                - npm run ci-test
          - step:
              name: Deploy to Expo
              trigger: manual
              deployment: production
              caches:
                - npm
              script:
                - apk add --no-cache bash
                - npm ci
                - npm install -g expo-cli 6.0.5
                - npx expo publish --non-interactive
    master:
      - step:
          name: Test with Jest
          caches:
            - npm
            - jest
          script:
            - npm ci
            - npm run ci-test
      - step:
          name: Deploy App
          deployment: staging
          caches: 
            - npm
          script:
            - apk add --no-cache bash
            - apk add --no-cache git
            - npm ci
            - npm install -g eas-cli
            - npm run build
      - step:
          name: Download IOS and Android Archives
          deployment: production
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - apk add --no-cache jq
            - apk add --no-cache git
            - apk add --no-cache wget
            - npm install -g eas-cli
            - wget -O android.apk $(eas build:list --json --limit=1 --platform=android | jq '.[0].artifacts.buildUrl' | cut -d "|" -f 2 | sed 's:^.\(.*\).$:\1:')
            - wget -O ios.tar.gz $(eas build:list --json --limit=1 --platform=ios | jq '.[0].artifacts.buildUrl' | cut -d "|" -f 2 | sed 's:^.\(.*\).$:\1:')
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "android.apk"
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "ios.tar.gz"